apiVersion: batch/v1
kind: Job
metadata:
  generateName: db-migrate-
  namespace: credreg-sandbox
  labels:
    app: main-app
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 900
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: main-app
    spec:
      serviceAccountName: main-app-service-account
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: 996810415034.dkr.ecr.us-east-1.amazonaws.com/registry:sandbox
          imagePullPolicy: Always
          command: ["/bin/bash","-lc","bundle exec rake db:migrate RACK_ENV=production"]
          envFrom:
            - secretRef:
                name: app-secrets
            - configMapRef:
                name: main-app-config
