apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: credreg-sandbox
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch-discovery
  replicas: 2
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      subdomain: elasticsearch-discovery
      priorityClassName: prod-high
      nodeSelector:
        env: sandbox
      tolerations:
        - key: "env"
          operator: "Equal"
          value: "sandbox"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: elasticsearch
              topologyKey: kubernetes.io/hostname
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:9.2.0
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "1000m"
              memory: "4Gi"
          readinessProbe:
            httpGet:
              path: /_cluster/health?wait_for_status=yellow&timeout=5s
              port: 9200
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
            - name: cluster.name
              value: "elasticsearch"
            - name: discovery.type
              value: "multi-node"
            - name: xpack.security.enabled
              value: "false"
            - name: network.host
              value: "0.0.0.0"
            - name: discovery.seed_hosts
              value: "elasticsearch-discovery"
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3
        resources:
          requests:
            storage: 20Gi
