apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: credreg-sandbox
  name: elasticsearch-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3
