
apiVersion: newrelic.com/v1beta2
kind: Instrumentation
metadata:
  name: newrelic-instrumentation
  namespace: newrelic
spec:
  agent:
    language: ruby

    image: newrelic/newrelic-ruby-init:latest
    env:
      - name: NEW_RELIC_APP_NAME
        value: Credential Engine Sandbox

  # Select a namespace with a specific name by using "kubernetes.io/metadata.name" label
  namespaceLabelSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: "In"
        values: ["credreg-sandbox"]

 # Select pods containing a specific label and value
 # podLabelSelector:
 #   matchExpressions:
 #     - key: "app.kubernetes.io/name"
 #       operator: "In"
 #       values: ["app1"]
