apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: credreg-sandbox
  name: opensearch-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2
