plugins:
  - rubocop-performance
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  ActiveSupportExtensionsEnabled: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - "bin/**/*"
    - "db/migrate/**/*"

Bundler/OrderedGems:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - lib/swagger_docs.rb
    - lib/swagger_helpers.rb

Metrics/MethodLength:
  Max: 15
  Exclude:
    - lib/swagger_helpers.rb

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
  AllowedMethods:
    ["resource", "namespace", "swagger_schema", "swagger_path", "included"]

# scope triggers a false positive, this will be fixed in rubocop 0.48.2
Lint/AmbiguousBlockAssociation:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 3

RSpec/NoExpectationExample:
  Enabled: false
