AllCops:
  TargetRubyVersion: 2.3

  DisplayCopNames: true

  DisplayStyleGuide: true

  Exclude:
    - 'db/structure.sql'

Style/ExtraSpacing:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false
