AllCops:
  TargetRubyVersion: 2.3

  DisplayCopNames: true

  DisplayStyleGuide: true

Style/ExtraSpacing:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - lib/swagger_docs.rb
    - lib/swagger_helpers.rb

Metrics/MethodLength:
  Exclude:
    - lib/swagger_helpers.rb
