language: ruby
rvm:
  - 2.3.1
  - 2.4.1
  - jruby-9.1.5.0

matrix:
  allow_failures:
    - rvm: 2.4.1
    - rvm: jruby-9.1.5.0

addons:
  postgresql: "9.4"

before_script:
  - createuser metadataregistry -s
  - psql -c 'create database metadataregistry_test;' -U postgres
  - bundle exec rake db:setup db:test:prepare schemas:load

script: bundle exec rspec
