version: "3"
services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.4.1
    expose:
      - 6379

  app:
    build: .
    image: credentialregistry-app:latest
    command: bash -c "bin/rake db:create db:migrate && bin/rackup -o 0.0.0.0"
    environment:
      - POSTGRESQL_ADDRESS=db
      - POSTGRESQL_DATABASE=cr_development
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RACK_ENV=production
      - DOCKER_ENV=true
    ports:
      - 9292:9292
    depends_on:
      - db
      - redis
    security_opt:
      - seccomp:unconfined

  worker:
    build: .
    image: credentialregistry-app:latest
    command: bash -c "bin/sidekiq -r ./config/application.rb"
    environment:
      - POSTGRESQL_ADDRESS=db
      - POSTGRESQL_DATABASE=cr_development
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RACK_ENV=production
      - DOCKER_ENV=true
      - STATEMENT_TIMEOUT=900000
    # no ports needed for worker
    depends_on:
      - db
      - redis
    security_opt:
      - seccomp:unconfined

volumes:
  postgres:
  rails_cache:
