version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.4.1
    expose:
      - 6379

  app_ubi10:
    image: registry:ubi10
    command: bash -c "bin/rake db:create db:migrate && bin/rackup -o 0.0.0.0"
    environment:
      - POSTGRESQL_ADDRESS=db
      - POSTGRESQL_DATABASE=cr_development
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RACK_ENV=production
      - DOCKER_ENV=true
    ports:
      - 9292:9292
    depends_on:
      - db
      - redis
    security_opt:
      - seccomp:unconfined

  worker_ubi10:
    image: registry:ubi10
    command: bash -c "bin/sidekiq -r ./config/application.rb"
    environment:
      - POSTGRESQL_ADDRESS=db
      - POSTGRESQL_DATABASE=cr_development
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RACK_ENV=production
      - DOCKER_ENV=true
      - STATEMENT_TIMEOUT=900000
    depends_on:
      - db
      - redis
    security_opt:
      - seccomp:unconfined

  app_navy:
    image: registry:ubi10-navy
    command: bash -c "bin/rake db:create db:migrate && bin/rackup -o 0.0.0.0"
    environment:
      - POSTGRESQL_ADDRESS=db
      - POSTGRESQL_DATABASE=cr_development
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RACK_ENV=production
      - DOCKER_ENV=true
    ports:
      - 9293:9292
    depends_on:
      - db
      - redis
    security_opt:
      - seccomp:unconfined

  worker_navy:
    image: registry:ubi10-navy
    command: bash -c "bin/sidekiq -r ./config/application.rb"
    environment:
      - POSTGRESQL_ADDRESS=db
      - POSTGRESQL_DATABASE=cr_development
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RACK_ENV=production
      - DOCKER_ENV=true
      - STATEMENT_TIMEOUT=900000
    depends_on:
      - db
      - redis
    security_opt:
      - seccomp:unconfined

volumes:
  postgres:
