services:
  db:
    image: postgres:16.10-alpine3.22
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:8.2.1-alpine
    expose:
      - 6379

  app:
    build: .
    image: credentialregistry-app:latest
    command: bash -c "bin/rake db:create db:migrate && bin/rackup -o 0.0.0.0"
    environment:
      - POSTGRESQL_ADDRESS=db
      - POSTGRESQL_DATABASE=cr_development
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RACK_ENV=production
      - DOCKER_ENV=true
      - ENVELOPE_GRAPHS_BUCKET=ce-registry-envelopes-staging
      - SWAGGER_ENABLED=true
      - IAM_CLIENT_ID=
      - IAM_COMMUNITY_CLAIM_NAME=
      - IAM_COMMUNITY_ROLE_ADMIN=
      - IAM_COMMUNITY_ROLE_PUBLISHER=
      - IAM_COMMUNITY_ROLE_READER=
      - IAM_ISSUER=
      - IAM_URL=
      # Publisher delivery
      - REGISTRY_CHANGESET_SYNC_ENDPOINT=
      - REGISTRY_CHANGESET_SYNC_DEBOUNCE_SECONDS=60
      - REGISTRY_CHANGESET_SYNC_ENDPOINT_TIMEOUT_SECONDS=60
      - REGISTRY_CHANGESET_SYNC_ENDPOINT_RETRY_INTERVAL_SECONDS=30

      # MinIO/S3
      - REGISTRY_CHANGESET_SYNC_BUCKET=
      - AWS_ENDPOINT_URL_S3=
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_EC2_METADATA_DISABLED=true

    ports:
      - 9292:9292
    depends_on:
      - db
      - redis
    security_opt:
      - seccomp:unconfined

  worker:
    build: .
    image: credentialregistry-app:latest
    command: bash -c "bin/sidekiq -r ./config/application.rb"
    environment:
      - POSTGRESQL_ADDRESS=db
      - POSTGRESQL_DATABASE=cr_development
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RACK_ENV=production
      - DOCKER_ENV=true
      - STATEMENT_TIMEOUT=900000
      - ENVELOPE_GRAPHS_BUCKET=ce-registry-envelopes-staging
      # Publisher delivery
      - REGISTRY_CHANGESET_SYNC_ENDPOINT=
      - REGISTRY_CHANGESET_SYNC_DEBOUNCE_SECONDS=
      - REGISTRY_CHANGESET_SYNC_ENDPOINT_TIMEOUT_SECONDS=
      - REGISTRY_CHANGESET_SYNC_ENDPOINT_RETRY_INTERVAL_SECONDS=

      # MinIO/S3
      - REGISTRY_CHANGESET_SYNC_BUCKET=
      - AWS_ENDPOINT_URL_S3=
      - AWS_S3_FORCE_PATH_STYLE=false
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_EC2_METADATA_DISABLED=true
    # no ports needed for worker
    depends_on:
      - db
      - redis
    security_opt:
      - seccomp:unconfined

volumes:
  postgres:
  rails_cache:
