version: '3'
services:
  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./log:/root/log:cached
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0.5-alpine
    expose:
      - 6379

  app:
    build: .
    command: bash -c "bundle install && bin/rackup -o 0.0.0.0"
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - 9292:9292
    depends_on:
      - db
      - redis

volumes:
  bundle:
  postgres:
  rails_cache:
