apiVersion: v1
kind: ConfigMap
metadata:
  name: main-app-config
data:
  POSTGRESQL_DATABASE: ceregistrystaging
  POSTGRESQL_USERNAME: ceregistrystaging
  RACK_ENV: production
  DOCKER_ENV: "true"
  ENVELOPE_GRAPHS_BUCKET: ce-registry-envelopes-staging
