apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: credreg-staging
  name: opensearch
  labels:
    app: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      securityContext:
        fsGroup: 1000   # ensure mounted volume is writable by OpenSearch user
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:3.3.1
          ports:
            - containerPort: 9200 # OpenSearch HTTP port
          resources:
            requests:
              cpu: "512m"
              memory: "4096Mi" 
            limits:
              cpu: "512m"
              memory: "4096Mi"
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms2048m -Xmx2048m"
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
            - name: cluster.name
              value: "opensearch"
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: "single-node"
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              value: "password" 
            - name: network.host
              value: "0.0.0.0"
            - name: http.cors.enabled
              value: "true"
            - name: http.cors.allow-origin
              value: "*"
            - name: indices.query.bool.max_clause_count
              value: "4096"
          securityContext:
            capabilities:
              add: ["IPC_LOCK"] 
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
      restartPolicy: Always
      volumes:
        - name: opensearch-data
          persistentVolumeClaim:
            claimName: opensearch-data
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
spec:
  selector:
    app: opensearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP
