apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-dump-service-account
  namespace: credreg-prod
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::996810415034:role/ce-registry-eks-db-dump-irsa-role"
    eks.amazonaws.com/token-expiration: "43200"
