---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secret
  namespace: credreg-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: credreg-secrets-eks-production

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-auth
  namespace: credreg-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: redis-auth
    creationPolicy: Owner
    template:
      data:
        password: "{{ .redis_password }}"
        redis-password.conf: |
          requirepass {{ .redis_password }}
  data:
    - secretKey: redis_password
      remoteRef:
        key: credreg-secrets-eks-production
        property: redis-password
