name: Dependency Review

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependecy-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019
        with:
          comment-summary-in-pr: on-failure
