name: Code Scanning

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  sonarqube:
    name: SonarQube Scan
    # Add this condition to run only in LT's fork
    if: github.repository == 'learningtapestry/CredentialRegistry'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@bfd4e558cda28cda6b5defafb9232d191be8c203
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
